version: "3.8"

services:
  photo-organizer:
    image: ghcr.io/trinculoliang/bobopic:main
    container_name: bobopic
    volumes:
      # 左侧是本地实际路径，右侧是容器内路径（固定）
      - "/Container/bobopic/in:/data/input"
      - "/Container/bobopic/out:/data/output"
      - "/Container/bobopic/bak:/data/backup"
    environment:
      # 可选：覆盖默认设置
      DRY_RUN: "false"           # true=预览，false=实际执行
      BACKUP_FOLDER: "/data/backup"  # 如果不需要备份，设为""空字符串
    command: organize            # 或 preview
